name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: docker
        run: |
          pwd
          docker pull hello-world

          ls .
          docker run hello-world

          docker images hello-world
        
